### ISSUE TITLE
error with peer c871d11439f226281bec0f1ae7a81984de2df30c: peer did not send us anything

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#10]
While syncing testnet data, the following error happened:

```
10:57PM INF committed state app_hash=D508E26B2702BA3052020FE8D3FCF6BB20C4BB5589CD0C9D85D19A4A77EAF555 height=18227 module=state num_txs=0
10:57PM INF indexed block height=18227 module=txindex
10:57PM INF minted coins from module account amount=21063460316073377727FX from=mint module=x/bank
10:57PM INF executed block height=18228 module=state num_invalid_txs=0 num_valid_txs=0
10:57PM INF commit synced commit=436F6D6D697449447B5B3136352039312032303420323033203137302032343120383420393320373120383220313933203236203234372032303920313332203233352037342031373320342032353220313837203234372036392032203133332032303120363320343120393720313633203133312039375D3A343733347D
10:57PM INF committed state app_hash=A55BCCCBAAF1545D4752C11AF7D184EB4AAD04FCBBF7450285C93F2961A38361 height=18228 module=state num_txs=0
10:57PM ERR SendTimeout module=blockchain peer=c871d11439f226281bec0f1ae7a81984de2df30c reason="peer did not send us anything" timeout=15000
10:57PM ERR Stopping peer for error err="error with peer c871d11439f226281bec0f1ae7a81984de2df30c: peer did not send us anything" module=p2p peer={"Data":{},"Logger":{}}
10:57PM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"3.220.32.240","port":26656}
10:57PM ERR Stopping peer for error err="read tcp 172.22.0.2:45068->3.220.32.240:26656: use of closed network connection" module=p2p peer={"Data":{},"Logger":{}}
10:57PM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"3.220.32.240","port":26656}
10:57PM ERR error while stopping peer error="already stopped" module=p2p
...
10:57PM ERR SendTimeout module=blockchain peer=cb9e91758f5ee581607b7099531845416cf1ab16 reason="peer did not send us anything" timeout=15000
10:57PM ERR Stopping peer for error err="error with peer cb9e91758f5ee581607b7099531845416cf1ab16: peer did not send us anything" module=p2p peer={"Data":{},"Logger":{}}
10:57PM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"52.205.107.141","port":26656}
10:57PM ERR Stopping peer for error err="read tcp 172.22.0.2:59926->52.205.107.141:26656: use of closed network connection" module=p2p peer={"Data":{},"Logger":{}}
10:57PM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"52.205.107.141","port":26656}
10:57PM ERR error while stopping peer error="already stopped" module=p2p
...
1:26PM ERR dialing failed (attempts: 6): dial tcp 3.212.91.184:26656: i/o timeout addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"3.212.91.184","port":26656} module=pex
1:26PM ERR dialing failed (attempts: 6): dial tcp 54.159.12.61:26656: i/o timeout addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"54.159.12.61","port":26656} module=pex
1:26PM ERR dialing failed (attempts: 6): dial tcp 52.205.107.141:26656: i/o timeout addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"52.205.107.141","port":26656} module=pex
1:26PM ERR dialing failed (attempts: 6): dial tcp 18.210.102.47:26656: i/o timeout addr={"id":"275f616954e149076b4eb1f726c44e9722ae00b6","ip":"18.210.102.47","port":26656} module=pex
1:26PM ERR dialing failed (attempts: 6): dial tcp 3.220.32.240:26656: i/o timeout addr={"id":"d2c3c6cec4c4412fcb70131574480db6819c65b9","ip":"3.220.32.240","port":26656} module=pex
1:26PM ERR dialing failed (attempts: 6): dial tcp 3.220.32.240:26656: i/o timeout addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"3.220.32.240","port":26656} module=pex
```

then the sync process stopped.

Any suggestion why this happened and how to deal with this? Maybe there is some faulty peers in the network or firewall issues?

**Comment by kenorb** [comment]
I've updated container image with testnet fixes as per GH-11, loaded data from the snapshot (2021-10-11), it's showing now testnet network correctly, but the above errors are still there:

```
3:27PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=30
3:27PM INF Will dial address addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=pex
3:27PM INF Will dial address addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=pex
3:27PM INF Will dial address addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=pex
3:27PM INF Will dial address addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=pex
3:27PM INF Dialing peer address={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=p2p
3:27PM INF Dialing peer address={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=p2p
3:27PM INF Dialing peer address={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=p2p
3:27PM ERR dialing failed (attempts: 7): dial tcp 18.138.204.122:26656: i/o timeout addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=pex
3:27PM ERR dialing failed (attempts: 7): dial tcp 18.138.204.122:26656: i/o timeout addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=pex
3:27PM ERR dialing failed (attempts: 7): dial tcp 18.138.204.122:26656: i/o timeout addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=pex
3:27PM INF Dialing peer address={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=p2p
3:27PM INF Error reconnecting to peer. Trying again addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} err="dial tcp 18.136.236.174:26656: i/o timeout" module=p2p tries=4
3:28PM INF Dialing peer address={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=p2p
3:28PM INF Error reconnecting to peer. Trying again addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} err="dial tcp 18.138.204.122:26656: i/o timeout" module=p2p tries=3
3:28PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=30
3:28PM INF Will dial address addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=pex
3:28PM INF Will dial address addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=pex
3:28PM INF Will dial address addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=pex
3:28PM INF Will dial address addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=pex
3:28PM INF Dialing peer address={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=p2p
3:28PM ERR dialing failed (attempts: 7): dial tcp 18.136.236.174:26656: i/o timeout addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=pex
3:28PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=30
3:28PM INF Will dial address addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=pex
3:28PM INF Will dial address addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=pex
3:28PM INF Will dial address addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=pex
3:28PM INF Will dial address addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=pex
```

Is it possible that other testnet peers blacklisted my node for requesting mainnet data due to wrong container image?

**Comment by zakir-code** [comment]
> While syncing testnet data, the following error happened:
> 
> ```
> 10:57PM INF committed state app_hash=D508E26B2702BA3052020FE8D3FCF6BB20C4BB5589CD0C9D85D19A4A77EAF555 height=18227 module=state num_txs=0
> 10:57PM INF indexed block height=18227 module=txindex
> 10:57PM INF minted coins from module account amount=21063460316073377727FX from=mint module=x/bank
> 10:57PM INF executed block height=18228 module=state num_invalid_txs=0 num_valid_txs=0
> 10:57PM INF commit synced commit=436F6D6D697449447B5B3136352039312032303420323033203137302032343120383420393320373120383220313933203236203234372032303920313332203233352037342031373320342032353220313837203234372036392032203133332032303120363320343120393720313633203133312039375D3A343733347D
> 10:57PM INF committed state app_hash=A55BCCCBAAF1545D4752C11AF7D184EB4AAD04FCBBF7450285C93F2961A38361 height=18228 module=state num_txs=0
> 10:57PM ERR SendTimeout module=blockchain peer=c871d11439f226281bec0f1ae7a81984de2df30c reason="peer did not send us anything" timeout=15000
> 10:57PM ERR Stopping peer for error err="error with peer c871d11439f226281bec0f1ae7a81984de2df30c: peer did not send us anything" module=p2p peer={"Data":{},"Logger":{}}
> 10:57PM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"3.220.32.240","port":26656}
> 10:57PM ERR Stopping peer for error err="read tcp 172.22.0.2:45068->3.220.32.240:26656: use of closed network connection" module=p2p peer={"Data":{},"Logger":{}}
> 10:57PM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"3.220.32.240","port":26656}
> 10:57PM ERR error while stopping peer error="already stopped" module=p2p
> ...
> 10:57PM ERR SendTimeout module=blockchain peer=cb9e91758f5ee581607b7099531845416cf1ab16 reason="peer did not send us anything" timeout=15000
> 10:57PM ERR Stopping peer for error err="error with peer cb9e91758f5ee581607b7099531845416cf1ab16: peer did not send us anything" module=p2p peer={"Data":{},"Logger":{}}
> 10:57PM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"52.205.107.141","port":26656}
> 10:57PM ERR Stopping peer for error err="read tcp 172.22.0.2:59926->52.205.107.141:26656: use of closed network connection" module=p2p peer={"Data":{},"Logger":{}}
> 10:57PM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"52.205.107.141","port":26656}
> 10:57PM ERR error while stopping peer error="already stopped" module=p2p
> ...
> 1:26PM ERR dialing failed (attempts: 6): dial tcp 3.212.91.184:26656: i/o timeout addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"3.212.91.184","port":26656} module=pex
> 1:26PM ERR dialing failed (attempts: 6): dial tcp 54.159.12.61:26656: i/o timeout addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"54.159.12.61","port":26656} module=pex
> 1:26PM ERR dialing failed (attempts: 6): dial tcp 52.205.107.141:26656: i/o timeout addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"52.205.107.141","port":26656} module=pex
> 1:26PM ERR dialing failed (attempts: 6): dial tcp 18.210.102.47:26656: i/o timeout addr={"id":"275f616954e149076b4eb1f726c44e9722ae00b6","ip":"18.210.102.47","port":26656} module=pex
> 1:26PM ERR dialing failed (attempts: 6): dial tcp 3.220.32.240:26656: i/o timeout addr={"id":"d2c3c6cec4c4412fcb70131574480db6819c65b9","ip":"3.220.32.240","port":26656} module=pex
> 1:26PM ERR dialing failed (attempts: 6): dial tcp 3.220.32.240:26656: i/o timeout addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"3.220.32.240","port":26656} module=pex
> ```
> 
> then the sync process stopped.
> 
> Any suggestion why this happened and how to deal with this? Maybe there is some faulty peers in the network or firewall issues?

The node information shown here is indeed provided by us. We are also surprised by the occurrence of `timeout`, we are looking for the problem

You can try to check whether the current node is synchronizing data through the following command, execute it every 5 seconds, and observe whether there is a change in `sync_info.latest_block_height`
```
ubuntu@ip-192-168-98-202:~$ curl -s http://127.0.0.1:26657/status
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "8",
        "block": "11",
        "app": "0"
      },
      "id": "12e5f084644059a360452ac1c1cb73d775434095",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "fxcore",
      "version": "v0.34.9",
      "channels": "40202122233038606100",
      "moniker": "your-moniker",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "056CFEB2A1351A81A3534BB5F4A691DBC8257AAC2DF3BD0E87B6B81BA60449E5",
      "latest_app_hash": "E2B1352D78B03E48F52F6241960B7337C0BFB0DA258E4DC990B8E4FA3181B78A",
      "latest_block_height": "2109095",
      "latest_block_time": "2021-11-15T02:32:57.688206878Z",
      "earliest_block_hash": "2C70CB931C1D958CDD3D68503CCD5D883D4B29579D9790D3FEF1E13BA45015DC",
      "earliest_app_hash": "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
      "earliest_block_height": "1",
      "earliest_block_time": "2021-07-05T04:00:00Z",
      "catching_up": false
    },
    "validator_info": {
      "address": "CFDA914942E70D821EE91B583CB7711AF00CF7D9",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "zJYtsWnl3E8AQG2o6j+A99dclZjEVR1R2UV772eVpF0="
      },
      "voting_power": "0"
    }
  }
}
```

**Comment by zakir-code** [comment]
> I've updated container image with testnet fixes as per [GH-11](https://github.com/FunctionX/fx-core/issues/11), loaded data from the snapshot (2021-10-11), it's showing now testnet network correctly, but the above errors are still there:
> 
> ```
> 3:27PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=30
> 3:27PM INF Will dial address addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=pex
> 3:27PM INF Will dial address addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=pex
> 3:27PM INF Will dial address addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=pex
> 3:27PM INF Will dial address addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=pex
> 3:27PM INF Dialing peer address={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=p2p
> 3:27PM INF Dialing peer address={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=p2p
> 3:27PM INF Dialing peer address={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=p2p
> 3:27PM ERR dialing failed (attempts: 7): dial tcp 18.138.204.122:26656: i/o timeout addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=pex
> 3:27PM ERR dialing failed (attempts: 7): dial tcp 18.138.204.122:26656: i/o timeout addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=pex
> 3:27PM ERR dialing failed (attempts: 7): dial tcp 18.138.204.122:26656: i/o timeout addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=pex
> 3:27PM INF Dialing peer address={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=p2p
> 3:27PM INF Error reconnecting to peer. Trying again addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} err="dial tcp 18.136.236.174:26656: i/o timeout" module=p2p tries=4
> 3:28PM INF Dialing peer address={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=p2p
> 3:28PM INF Error reconnecting to peer. Trying again addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} err="dial tcp 18.138.204.122:26656: i/o timeout" module=p2p tries=3
> 3:28PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=30
> 3:28PM INF Will dial address addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=pex
> 3:28PM INF Will dial address addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=pex
> 3:28PM INF Will dial address addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=pex
> 3:28PM INF Will dial address addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=pex
> 3:28PM INF Dialing peer address={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=p2p
> 3:28PM ERR dialing failed (attempts: 7): dial tcp 18.136.236.174:26656: i/o timeout addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=pex
> 3:28PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=30
> 3:28PM INF Will dial address addr={"id":"cb9e91758f5ee581607b7099531845416cf1ab16","ip":"18.138.204.122","port":26656} module=pex
> 3:28PM INF Will dial address addr={"id":"43b849debb6e2b5ffed246b76da0a7a93d14bb84","ip":"18.136.236.174","port":26656} module=pex
> 3:28PM INF Will dial address addr={"id":"eef28254833827b4ff0e43d78d6a0ff81a41bbd0","ip":"18.138.204.122","port":26656} module=pex
> 3:28PM INF Will dial address addr={"id":"c871d11439f226281bec0f1ae7a81984de2df30c","ip":"18.138.204.122","port":26656} module=pex
> ```
> 
> Is it possible that other testnet peers blacklisted my node for requesting previously invalid network data (mainnet instead of testnet) due to wrong container image? Because of that, my node cannot sync any new data.

The node information shown here is not provided by us. It may be a node run by others in the community. Maybe you can try to pause the node first, then `rm .fxcore/config/addrbook.json` to start the node again

**Comment by kenorb** [comment]
> The node information shown here is not provided by us. It may be a node run by others in the community. Maybe you can try to pause the node first, then `rm .fxcore/config/addrbook.json` to start the node again

I've tried to remove `addrbook.json`, but it didn't help much, after restart it was the same.
At the end I did another resync from scratch and it worked on its own.
