### ISSUE TITLE
fxcored prune

### ISSUE THREAD

**Issue by FrenchXCore** [FunctionX/fx-core#102]
## Summary of Bug

When calling `fxcored prune` without argument from the CLI, the app goes panic.
Although the command should be rejected, it should not provoke panicking.

## Version

v4.2.x-4.2.1

## Steps to Reproduce

`fxcored prune` from the CLI

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by devon-chain** [comment]
@FrenchXCore Thanks for opening the issue. This can cause panic because the default home directory is empty. we will fix it.
