### ISSUE TITLE
'fxcored' status returned on stderr, not stdout

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#12]
When run `fxcored status` it prints JSON (without errors, rc=0), however it is still printed to stderr, not stdout.
Not sure if this is expected, it doesn't make sense much to print a regular JSON to stderr. And also makes an additional effort to format or parse JSON (e.g. `fxcored status 2>&1 | jq`).

**Comment by zakir-code** [comment]
This is a good issues, I will consider fixing it, and we will check similar problems at the same time, thank you for your feedback

**Comment by zakir-code** [comment]
this has been fixed on ab9780eecc105512e9db21a50ef500e8819da7d0
