### ISSUE TITLE
Error: ledger nano S: support for ledger devices is not available in this executable

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#13]
When using Docker container for testnet, I've got the following error when adding the key:

```
$ fxcored keys add foo --ledger
Error: ledger nano S: support for ledger devices is not available in this executable
```

I think ledger support should be added to the binary?

**Comment by zakir-code** [comment]
We set the ledger to be disabled in the `linux` os, you can try to install `fxcored` in your `mac` or `windows` os by `make install`, it is supports ledger
