### ISSUE TITLE
cosmovisor: panic: invalid chainId: fx-zakir

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#137]
## Summary of Bug

I'm trying to initialize and run validator using `cosmovisor`, but I've got the following errors;

```
fxcore:~$ cosmovisor init /usr/bin/fxcored
5:35PM INF checking on the genesis/bin directory module=cosmovisor
5:35PM INF creating directory (and any parents): "/home/fxcore/.fxcore/cosmovisor/genesis/bin" module=cosmovisor
5:35PM INF checking on the genesis/bin executable module=cosmovisor
5:35PM INF copying executable into place: "/home/fxcore/.fxcore/cosmovisor/genesis/bin/fxcored" module=cosmovisor
5:35PM INF making sure "/home/fxcore/.fxcore/cosmovisor/genesis/bin/fxcored" is executable module=cosmovisor
5:35PM INF checking on the current symlink and creating it if needed module=cosmovisor
5:35PM INF the current symlink points to: "/home/fxcore/.fxcore/cosmovisor/genesis/bin/fxcored" module=cosmovisor

fxcore:~$ /usr/bin/fxcored init fx-zakir --overwrite --chain-id fx-zakir

fxcore:~$ /usr/bin/cosmovisor run start --x-crisis-skip-assert-invariants
5:37PM INF replace cosmovisor module=cosmovisor replace-flag=false
5:37PM INF running app args=["start","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/fxcore/.fxcore/cosmovisor/genesis/bin/fxcored
panic: invalid chainId: fx-zakir

goroutine 1 [running]:
github.com/functionx/fx-core/v4/types.SetChainId({0xc001b17ee0?, 0x3d2f?})
	github.com/functionx/fx-core/v4/types/version.go:42 +0xcc
github.com/functionx/fx-core/v4/server.StartCmd.func1(0xc0010f8300?, {0xc00101df20?, 0x0?, 0x1?})
	github.com/functionx/fx-core/v4/server/start.go:115 +0x2c5
github.com/spf13/cobra.(*Command).execute(0xc0010f8300, {0xc00101df00, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:925 +0x7db
github.com/spf13/cobra.(*Command).ExecuteC(0xc0018f6c00)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x2425e10?, {0x29f652c, 0x2}, {0xc000c4ba58, 0x14})
	github.com/cosmos/cosmos-sdk@v0.46.13/server/cmd/execute.go:36 +0x20f
main.main()
	github.com/functionx/fx-core/v4/cmd/fxcored/main.go:14 +0x38
Error: exit status 2
5:37PM ERR error="exit status 2" module=cosmovisor
```

If I do `cosmovisor init /usr/bin/fxcored`, but without `fxcored init`, then `cosmovisor run start`, I've different error:

> Error: couldn't read GenesisDoc file: open /home/fxcore/.fxcore/config/genesis.json: no such file or directory

Changing the order doesn't help either.

What I'm doing wrong?
What commands should I run to initialize fxcored with cosmovisor correctly?

## Version

```
fxcore:~$ fxcored version
release/v4.2.x-v4.2.2
fxcore:~$ cosmovisor version
cosmovisor version: devel-214c176dd766220aee7873f5ed958eaed46b21e7
app version: release/v4.2.x-v4.2.2
```

I'm using Docker version.

## Steps to Reproduce

```
cosmovisor init /usr/bin/fxcored
fxcored init fx-zakir --overwrite --chain-id fx-zakir
cosmovisor run start --x-crisis-skip-assert-invariants
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by zakir-code** [comment]
@kenorb Please refer to the [documentation](https://functionx.gitbook.io/home/upgrade-instructions/cosmovisor/tutorial-binaries)

**Comment by zakir-code** [comment]
fxcored does not support custom chainId

**Comment by kenorb** [comment]
> fxcored does not support custom chainId

`--chain-id fx-zakir` was suggested at https://github.com/FunctionX/fx-core/issues/84#issuecomment-1580176437, otherwise I had different error about non-empty chain_id.

**Comment by kenorb** [comment]
> Please refer to the [documentation](https://functionx.gitbook.io/home/upgrade-instructions/cosmovisor/tutorial-binaries)

I'm using Docker container and at <https://functionx.gitbook.io/home/upgrade-instructions/cosmovisor/tutorial-docker> there is nothing how to do `init`.

In the link that you've sent, it's only `cosmovisor init ./build/bin/fxcored`.

So in my case after I do `cosmovisor init /usr/bin/fxcored`, I've got the following error:

> Error: couldn't read GenesisDoc file: open /home/fxcore/.fxcore/config/genesis.json: no such file or directory

So my question is, how to do `init` using `cosmovisor`, so initial `config/genesis.json` can be created?

**Comment by zakir-code** [comment]
> > Please refer to the [documentation](https://functionx.gitbook.io/home/upgrade-instructions/cosmovisor/tutorial-binaries)
> 
> I'm using Docker container and at https://functionx.gitbook.io/home/upgrade-instructions/cosmovisor/tutorial-docker there is nothing how to do `init`.
> 
> In the link that you've sent, it's only `cosmovisor init ./build/bin/fxcored`.
> 
> So in my case after I do `cosmovisor init /usr/bin/fxcored`, I've got the following error:
> 
> > Error: couldn't read GenesisDoc file: open /home/fxcore/.fxcore/config/genesis.json: no such file or directory
> 
> So my question is, how to do `init` using `cosmovisor`, so initial `config/genesis.json` can be created?

genesis.json can be downloaded using wget.

ref: https://functionx.gitbook.io/home/fxcore/setup-node/full-node-with-docker

If you want to connect to other peers, you need to download the config.toml file, which contains some seed peer information.

**Comment by zakir-code** [comment]
> > fxcored does not support custom chainId
> 
> `--chain-id fx-zakir` was suggested at [#84 (comment)](https://github.com/FunctionX/fx-core/issues/84#issuecomment-1580176437), otherwise I had different error about non-empty chain_id.

Sorry, please refer https://functionx.gitbook.io/home/fxcore/setup-node/full-node-with-binaries
