### ISSUE TITLE
Missing 4.2.2 fxcore image at ghcr.io

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#138]
## Summary of Bug

Missing `4.2.2` image on GitHub at https://github.com/functionx/fx-core/pkgs/container/fx-core.

This version is available at Docker's Hub at https://hub.docker.com/r/functionx/fx-core/tags

Can this version be pushed to GitHub Packages as well for consistency?

## Version

n/a

## Steps to Reproduce

n/a

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by zakir-code** [comment]
@kenorb Hi, Thank you for your feedback. Sorry, v4.2.2 was not adopted in the end. Please use other correct versions. The historical upgrade version of fxcore can be found [here](https://functionx.gitbook.io/home/upgrade-instructions/versions)

ref: https://github.com/FunctionX/fx-core/releases/tag/v4.2.2-rc1
