### ISSUE TITLE
Amount not shown when running 'query account'

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#14]
I'm quering the balance of the account on testnet using `fxcored` command (from Docker container), but it doesn't show any amount.

```
$ fxcored query account fx1s3ye9y8hgg26wqkysvkdavcngg4syfdzejgqt2
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "10"
address: fx1s3ye9y8hgg26wqkysvkdavcngg4syfdzejgqt2
pub_key:
  '@type': /cosmos.crypto.secp256k1.PubKey
  key: AxOA/4K78GEzTT/dY7jJcBZtKohYH5IVVqtgYRfCveGH
sequence: "55"
```

despite the balance is shown in the [Explorer](https://aabbcc-explorer.functionx.io/fxcore/address/fx1s3ye9y8hgg26wqkysvkdavcngg4syfdzejgqt2).

I believe there should be `amount` field.

**Comment by zakir-code** [comment]
`fxcored query bank balances [address]`

**Comment by kenorb** [comment]
> `fxcored query bank balances [address]`

It works, thanks.

**Comment by kenorb** [comment]
However according to [Gaia Client docs](https://github.com/cosmos/gaia/blob/main/docs/resources/gaiad.md#query-account-balance), `query account` sub-command should work as well in order to view your account's balance.

**Comment by zakir-code** [comment]
> Btw. As a side-note, according to [Gaia Client docs](https://github.com/cosmos/gaia/blob/main/docs/resources/gaiad.md#query-account-balance), `query account` sub-command should work as well in order to view your account's balance.

`cosmos-sdk` has separated `query account` and `query balances`, and `gaia` is the same. It should be that their documents have not been updated in time. [cosmos-sdk ChangLog](https://github.com/cosmos/cosmos-sdk/blob/master/CHANGELOG.md#state-machine-breaking-3)
