### ISSUE TITLE
Provide date-fixed snapshot aliases/files dumps (e.g. snapshot-mainnet-latest.tar.gz)

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#140]
## Summary

Can you do aliases for provided snapshot links?

E.g. instead of `fxcore-pruned-snapshot-mainnet-2023-02-08.tar.gz`, make it `fxcore-pruned-snapshot-mainnet-latest.tar.gz`.

## Problem Definition

I've `docker-compose.yml` where I hardcode links to dumps, but this needs to be scripted to dynamically calculate the yesterday's date. So the easiest approach would be to provide standarized links to the latest available dumps, instead of guessing the dates (whether it's today if the dump was already done, or yesterday or another date).

## Proposal

Links to dumps should be like:

- `fxcore-pruned-snapshot-mainnet-latest.tar.gz` (or nightly)
- `fxcore-snapshot-mainnet-latest.tar.gz`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by zakir-code** [comment]
@kenorb Sorry, we think it is necessary to add the exact date to the file name, if you expect to get the current date, this can be done with some scripts.

Snapshots are taken every day at 10am GMT +8 and may take several hours to take, so see if this script can help you:

```shell
# if current hour is greater than 16, then use today's date, otherwise use yesterday's date
if [ $((10#$(date -u +"%H") + 8)) -gt 16 ]; then
  date +%Y-%m-%d
else
  date -r $((10#$(date +%s) - 86400)) +%Y-%m-%d
fi
```

**Comment by kenorb** [comment]
Ok, thanks.
I did as follow:

```
FXSNAPURL=${FXSNAPURL:-https://fx-${FXNET}.s3.amazonaws.com/fxcore-pruned-snapshot-${FXNET}-$(date +%Y-%m-%d).tar.gz}
```

but it's always taking the previous day, your could be better, but longer.

Another thing I've noticed is that testnet URL isn't consistent with mainnet (`fx-mainnet.` vs `testnet-fx.`).

I'm ok at this point. Feel free to close it.
