### ISSUE TITLE
Error: failed to initialize database: resource temporarily unavailable

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#15]
```
$ fxcored export
Error: failed to initialize database: resource temporarily unavailable
...
```

Not sure if this should happen (testnet). Are there any steps how to initialize database, or it's a bug?

**Comment by zakir-code** [comment]
Are you running `fxcored start`, `fxcored export` needs to read the database, but the database can only be opened by one program, so you can check whether there are other programs that have occupied the database resources.

**Comment by kenorb** [comment]
Make sense, the `start` process was running. It did work when it wasn't. Thanks.

**Comment by kenorb** [comment]
Small typo in `fxcored export -h`:

> Export state to start at height zero (perform **preproccessing**)

Should be: **preprocessing**.

**Comment by zakir-code** [comment]
Check if there is a running fxcored process
`ps -ef | grep -v grep | grep fxcored` 

Or, use `lsof` to find the process that has the file open
`lsof +D $HOME/.fxcore/data`
