### ISSUE TITLE
Missing output format for 'query txs' command

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#21]
I'm comparing `fxcored query tx -h` with `fxcored query txs -h` and `txs` has the following option missing:

>  -o, --output string   Output format (text|json) (default "text")

In addition the same `txs` command resulted in JSON output (eb07c079d46142e1ad698fa85d9657e928159d52), and when using the latest version it's printing YAML instead (290422190841203478a9465ed4803ee346caf9e0).

I think it would be great that user can choose between two formats (and YAML as the default option, similar like with other commands).

**Comment by zakir-code** [comment]
Yes, we think so too, we are checking and fixing similar format output problems, thank you for your feedback

**Comment by zakir-code** [comment]
fixed on 31250dde781852f92cf9a62a138a169230a47a7b
