### ISSUE TITLE
Node param (`-n`/`--node`) inconsistency

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#22]
```
$ fxcored query txs -h
...
  -n, --node string              Node to connect to (default "tcp://localhost:26657")
```

vs

```
$  fxcored query tx -h
...
      --node string     <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
```

or

```
$ fxcored query other gasPrice -h
...
      --node string     <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
```

Some command accepts `-n` as a short for `--node `, some not. It's confusing and it would be great to make it consistent (by having both options). Also param description isn't consistent either. In addition, ideally to have some environmental variable specifying a node to connect to (so the node address doesn't have to be repeated in every command).

**Comment by zakir-code** [comment]
I think so, we will upgrade `cosmos-sdk` to fix the problem
