### ISSUE TITLE
query slashing signing-infos: Error: accepts 1 arg(s), received 0

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#24]
It's not clear what kind of argument this command expects:

```
$ fxcored query slashing signing-infos   
Error: accepts 1 arg(s), received 0
Usage:
  fxcored query slashing signing-infos [flags]
```

but this works fine:

```
$ fxcored query slashing signing-infos ""
```

So if there is no any real argument for this command, it shouldn't error.

Although I'm reading at <https://github.com/cosmos/gaia/issues/624> it expects `cons_address`? However when provided the specific address, the list stays the same.

**Comment by zakir-code** [comment]
This is a bug, we have fixed it in 9ba99411061a4926c0892d07aabb4bbb2ae62b23
