### ISSUE TITLE
Improve error for 'tx staking delegate'

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#26]
When running the following command, it's not clear what it's missing (the error doesn't help much):

```
$ fxcored tx staking delegate fxvaloper1... 1000..FX 
Error: empty delegator address
Usage:
  fxcored tx staking delegate [validator-addr] [amount] [flags]

Flags:
  -a, --account-number uint      The account number of the signing account (offline mode only)
  -b, --broadcast-mode string    Transaction broadcasting mode (sync|async|block) (default "sync")
      --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it
      --fees string              Fees to pay along with transaction; eg: 10uatom
      --from string              Name or address of private key with which to sign
... 14 more params to guess which is missing.
```

And there is no indication which flags are mandatory. When using this command often, you know that you've to use `--from`, however it's not clear for a person using this command for the first time.

Maybe by updating usage by adding `--from [delegator-addr]`, or marking mandatory next to `--fees`?

**Comment by zakir-code** [comment]
Generally speaking, when using `fxcored tx ...` to send a transaction, it is necessary to set the signer of the transaction through `--from`, except that `fxcored tx bank send` can be omitted
