### ISSUE TITLE
How to reload config without the process restart?

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#28]
I've changed log level to 'warn' and I'd like to reload the config without restarting the whole process, is it possible?

I've tested, and `fxcored` process doesn't react on SIGHUP signal.

E.g.

```
$ fxcored config config.toml log_level warn
update configuration file: /home/fxcore/.fxcore/config
$ fxcored config config.toml log_level
"warn"

$ ps wuax
...
fxcore         8 13.6  1.4 1247456 455996 ?      Sl   Nov23 736:03 /usr/bin/fxcored start

$ kill -SIGHUP 8
```

I've checked the logs,  but nothing happened, no any info messages appeared after a signal has been sent.

But the signal HUP is ignored. Is it possible to support the signal or another option to reload the config after change, or maybe there is another graceful reload command?

**Comment by zakir-code** [comment]
Sorry, there is currently no such feature
