### ISSUE TITLE
Output support for 'fxcored query block'

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#34]
The `fxcored query block` command lacks of output format. E.g. default it prints JSON, not YAML, and there is no option to change that.

Related: GH-23.

```
$ fxcored version
master-cecc3f6a56867c8d3d4bc2dffca2c4dd3258e07d
```

**Comment by zakir-code** [comment]
fixed on 9ba99411061a4926c0892d07aabb4bbb2ae62b23
