### ISSUE TITLE
unjail: no error, no transaction

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#38]
```
$ fxcored tx slashing unjail --from mykey --keyring-backend test --yes
code: 0
codespace: ""
data: ""
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: '[]'
timestamp: ""
tx: null
txhash: 2474C7965F88D865D58823B6FD18FF527FD101D8C85FE1A598C116CF6B090062
```

It gives no error, but it uses 0 gas and given txhash doesn't exist.

Although running with dry, it gives the actual error:

```
$ fxcored tx slashing unjail --from mykey --keyring-backend test --yes --dry-run
Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 22, got 21: incorrect account sequence: invalid request
```

Shouldn't the normal command error as well?

**Comment by zakir-code** [comment]
You can use `--broadcast-mode block` to modify the transaction broadcast mode and check whether the nodes connected to fxcored have been synchronized

**Comment by kenorb** [comment]
When sending a transaction (`tx bank send`), it's doing a block mode by default.
Is there any reason why different commands have different modes by default?

**Comment by zakir-code** [comment]
If you do not set the flags parameter, the default values of commonly used parameters of `fxcored` are set through `client.toml`, you can query the default query through `fxcored config`, `fxcored config <key> <value>` to modify the default value
