### ISSUE TITLE
Internal error: code: -32603

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#41]
When going to http://mytestnetnode:26657/broadcast_evidence I've got the following error:

```
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "no evidence was provided"
  }
}
```

I've checked on the docs, and there is no such error: https://functionx.gitbook.io/home/developers/json-rpc-api#response-20

Any idea what does it mean? Validator is up and running fine.

**Comment by zakir-code** [comment]
This error is a standard JSON-RPC2.0 error, the meaning of the error can be found in the [JSON-RPC specification document](https://www.jsonrpc.org/specification)

**Comment by kenorb** [comment]
Thanks.

> -32603 | Internal error | Internal JSON-RPC error.

Any suggestion what -32603 error may be? It happens on each refresh of the page.

**Comment by zakir-code** [comment]
[This API](https://functionx.gitbook.io/home/developers/json-rpc-api#broadcastevidence) needs to set a parameter `?evidence=`
