### ISSUE TITLE
Support for config client.toml

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#42]
```
$ fxcored config client.toml
Error: couldn't get the value for the key: client.toml, error:  unknown configuration key: "client.toml"

$ fxcored config -h
...
Available Commands:
  app.toml    Create or query an `.fxcore/config/apptoml` file
  config.toml Create or query an `.fxcore/config/config.toml` file
...
```

Is it possible to you add support for "client.toml" configuration file, such as changing the default "chain-id"?

**Comment by zakir-code** [comment]
There are some differences for `client.toml`
use `fxcored config` to query client.toml information
user `fxcored config chain-id fxcore` Modify chain-id
