### ISSUE TITLE
Error in Building testnet binanry

### ISSUE THREAD

**Issue by aman-rac** [FunctionX/fx-core#49]
@zakir-code , I get 
```
make go.sum
Makefile:207: *** target pattern contains no '%'.  Stop.
```
My branch:
```
make go.sum
Makefile:207: *** target pattern contains no '%'.  Stop.
```
It is related to incorrect spaces in Makefile.

**Comment by aman-rac** [comment]
The issue was a : present in my GOPATH, fixed it with this

```
-STATIK = $(GOPATH)/bin/statik
+STATIK = $(echo $GOPATH | sed -e "s/[:]/\\\:/g")/bin/statik
```
But later had issue with make install-testnet so I had to change the GOPATH anyhow. Btw the testnet build instruction [here](https://functionx.gitbook.io/home/f-x-core/installation) aren't working with the HEAD of the branch, had to reset to the dhobyghaut tag [commit](https://github.com/FunctionX/fx-core/commit/46bca00af59765e75902a1e7f07915c87b3b3bfd).

**Comment by zakir-code** [comment]
Sorry our documentation is not up to date.
After v2.1.0, testnet and Mainnet are installed in the same way: make install

**Comment by zakir-code** [comment]
https://functionx.gitbook.io/home/f-x-core/installation
