### ISSUE TITLE
Can you make Dockerfile rootless?

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#5]
I'd like to setup a node using Docker container, however I would like to setup as non-root.

Currently `Dockerfile` is using `root`, and when I've run it by a regular user, however the container is still creating the files in `~/.fxcore` as root (when that directory is mounted), because inside container it's running as root.

**Comment by RichardNgKongYeow** [comment]
when running fxcored using the docker container, you can use the docker run -d --user <uid> -v $HOME/.fxcore:/fxcore functionx/fx-core:mainnet start --home /fxcore Set the identity for the docker container to run and modify the default home directory

**Comment by RichardNgKongYeow** [comment]
on this note, in fact, is for running a separate tendermint program (consensus layer), fxcored is a specific application that can only be modified by flag-home at the moment

**Comment by zakir-code** [comment]
Yes, we currently run the docker container using root by default. 

If you want to run the container as non-root, There are two solutions:
1. Use options `--user` when running the docker container
2. you can use the following `Dockerfile` contents (insert before ENTRYPOINT.)
`
# Create a group and user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# Tell docker that all future commands should run as the appuser user
USER appuser
WORKDIR appuser
`
RUN: `make docker`

**Comment by kenorb** [comment]
Works for me, thanks.
