### ISSUE TITLE
'query slashing signing-info' doesn't accept format from 'tendermint show-address' anymore

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#55]
```
$ fxcored query slashing signing-info $(fxcored tendermint show-address)
Error: invalid character 'x' in literal false (expecting 'a')
$ fxcored version
HEAD-8f2f0f7bf917eac2b405db497a21a0b3c5073f86
```

**Comment by fx0x55** [comment]
can you try with `fxcored q slashing signing-info $(fxcored tendermint show-validator)`

**Comment by kenorb** [comment]
Yes, suggested command works fine.

In this case, does `fxcored query slashing signing-info` command have any usage or it should be removed?

**Comment by fx0x55** [comment]
q is an alias for query

`fxcored q == fxcored query`
